import React from 'react';

export function Dashboard({ onNavigate }: { onNavigate: (tab: string) => void }) {
  return <div className="min-h-[calc(100vh-140px)] bg-[#061326] rounded-2xl p-6 text-white space-y-6">
    <section className="rounded-2xl border border-cyan-900 bg-gradient-to-r from-[#0b2646] to-[#10213a] p-8 flex items-center justify-between">
      <div><p className="text-cyan-300 text-lg">AI → MCP → CapCut Desktop</p><h1 className="text-4xl font-bold mt-2">CapCut Bridge Kit</h1><p className="text-slate-300 mt-3">Open Source Bridge for AI-Assisted Video Editing</p></div>
      <div className="text-right"><span className="rounded-full border border-emerald-400/50 px-4 py-2 text-emerald-300">● Bridge Online</span><span className="ml-3 rounded-full border border-cyan-400/50 px-4 py-2 text-cyan-300">MCP Connected</span></div>
    </section>
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4">{[['Active Project','My Reel','Draft: My_Reel_01'],['Media','24','clips & assets'],['Sequences','1','timeline'],['Bridge Status','ONLINE','All systems operational']].map(([a,b,c])=><div className="rounded-xl border border-cyan-900 bg-[#0b1d35] p-5" key={a}><div className="text-slate-300">{a}</div><div className="text-2xl font-bold mt-3">{b}</div><div className="text-slate-400 text-sm">{c}</div></div>)}</div>
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-5"><section className="lg:col-span-2 rounded-xl border border-cyan-900 bg-[#0b1d35] p-6"><h2 className="text-xl font-semibold">Project Overview</h2><div className="mt-5 grid grid-cols-2 gap-4 text-slate-300"><div>Project Name<br/><b className="text-white">My Reel</b></div><div>Draft Name<br/><b className="text-white">My_Reel_01</b></div><div>Media Files<br/><b className="text-white">24 clips</b></div><div>Timeline Duration<br/><b className="text-white">00:42</b></div></div><button onClick={()=>onNavigate('studio')} className="mt-6 rounded-lg bg-cyan-500 px-5 py-3 font-semibold text-slate-950">Open in CapCut</button></section><section className="rounded-xl border border-cyan-900 bg-[#0b1d35] p-6"><h2 className="text-xl font-semibold">Quick Actions</h2><div className="grid grid-cols-2 gap-3 mt-5">{[['Create Project','studio'],['Add Media','studio'],['Split','timeline'],['Export','studio'],['Add Text','studio']].map(([label,tab])=><button key={label} onClick={()=>onNavigate(tab)} className="rounded-lg border border-slate-700 p-4 text-left hover:border-cyan-400">{label}</button>)}</div></section></div>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-5"><section className="rounded-xl border border-emerald-800 bg-emerald-950/30 p-6"><h2 className="text-xl font-semibold text-emerald-300">File Lane</h2><p className="text-slate-300 mt-2">Manage draft structure, media and JSON timeline edits.</p></section><section className="rounded-xl border border-violet-800 bg-violet-950/30 p-6"><h2 className="text-xl font-semibold text-violet-300">Live Lane</h2><p className="text-slate-300 mt-2">Desktop automation with keyboard shortcuts and export workflow.</p></section></div>
  </div>;
}
